package co.edu.usbcali.modelo;
// Generated 10-mar-2018 20:23:35 by Hibernate Tools 5.2.3.Final

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * MenuSemana generated by hbm2java
 */
public class MenuSemana implements java.io.Serializable {

	private int id;
	private Bebida bebida;
	private Principio principio;
	private Proteina proteina;
	private Sopa sopa;
	private String dia;
	private Integer idBebida;
	private String estado;
	private Date fechaInicio;
	private Date fechaFin;
	private Set<Almuerzo> almuerzos = new HashSet<Almuerzo>(0);

	public MenuSemana() {
	}

	public MenuSemana(int id, Bebida bebida, Principio principio, Proteina proteina, Sopa sopa) {
		this.id = id;
		this.bebida = bebida;
		this.principio = principio;
		this.proteina = proteina;
		this.sopa = sopa;
	}

	public MenuSemana(int id, Bebida bebida, Principio principio, Proteina proteina, Sopa sopa, String dia,
			Integer idBebida, String estado, Date fechaInicio, Date fechaFin, Set<Almuerzo> almuerzos) {
		this.id = id;
		this.bebida = bebida;
		this.principio = principio;
		this.proteina = proteina;
		this.sopa = sopa;
		this.dia = dia;
		this.idBebida = idBebida;
		this.estado = estado;
		this.fechaInicio = fechaInicio;
		this.fechaFin = fechaFin;
		this.almuerzos = almuerzos;
	}

	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	public Bebida getBebida() {
		return this.bebida;
	}

	public void setBebida(Bebida bebida) {
		this.bebida = bebida;
	}

	public Principio getPrincipio() {
		return this.principio;
	}

	public void setPrincipio(Principio principio) {
		this.principio = principio;
	}

	public Proteina getProteina() {
		return this.proteina;
	}

	public void setProteina(Proteina proteina) {
		this.proteina = proteina;
	}

	public Sopa getSopa() {
		return this.sopa;
	}

	public void setSopa(Sopa sopa) {
		this.sopa = sopa;
	}

	public String getDia() {
		return this.dia;
	}

	public void setDia(String dia) {
		this.dia = dia;
	}

	public Integer getIdBebida() {
		return this.idBebida;
	}

	public void setIdBebida(Integer idBebida) {
		this.idBebida = idBebida;
	}

	public String getEstado() {
		return this.estado;
	}

	public void setEstado(String estado) {
		this.estado = estado;
	}

	public Date getFechaInicio() {
		return this.fechaInicio;
	}

	public void setFechaInicio(Date fechaInicio) {
		this.fechaInicio = fechaInicio;
	}

	public Date getFechaFin() {
		return this.fechaFin;
	}

	public void setFechaFin(Date fechaFin) {
		this.fechaFin = fechaFin;
	}

	public Set<Almuerzo> getAlmuerzos() {
		return this.almuerzos;
	}

	public void setAlmuerzos(Set<Almuerzo> almuerzos) {
		this.almuerzos = almuerzos;
	}

}
