package co.edu.usbcali.modelo;
// Generated 10-mar-2018 20:23:35 by Hibernate Tools 5.2.3.Final

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Hijo generated by hbm2java
 */
public class Hijo implements java.io.Serializable {

	private int id;
	private Padre padre;
	private Usuario usuario;
	private Date fechaNacimiento;
	private String curso;
	private int usuarioid;
	private String usuarioCreacion;
	private Date fechaCreacion;
	private String usuarioModifica;
	private Date fechaModifica;
	private Set<Almuerzo> almuerzos = new HashSet<Almuerzo>(0);

	public Hijo() {
	}

	public Hijo(int id, Usuario usuario, int usuarioid) {
		this.id = id;
		this.usuario = usuario;
		this.usuarioid = usuarioid;
	}

	public Hijo(int id, Padre padre, Usuario usuario, Date fechaNacimiento, String curso, int usuarioid,
			String usuarioCreacion, Date fechaCreacion, String usuarioModifica, Date fechaModifica,
			Set<Almuerzo> almuerzos) {
		this.id = id;
		this.padre = padre;
		this.usuario = usuario;
		this.fechaNacimiento = fechaNacimiento;
		this.curso = curso;
		this.usuarioid = usuarioid;
		this.usuarioCreacion = usuarioCreacion;
		this.fechaCreacion = fechaCreacion;
		this.usuarioModifica = usuarioModifica;
		this.fechaModifica = fechaModifica;
		this.almuerzos = almuerzos;
	}

	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	public Padre getPadre() {
		return this.padre;
	}

	public void setPadre(Padre padre) {
		this.padre = padre;
	}

	public Usuario getUsuario() {
		return this.usuario;
	}

	public void setUsuario(Usuario usuario) {
		this.usuario = usuario;
	}

	public Date getFechaNacimiento() {
		return this.fechaNacimiento;
	}

	public void setFechaNacimiento(Date fechaNacimiento) {
		this.fechaNacimiento = fechaNacimiento;
	}

	public String getCurso() {
		return this.curso;
	}

	public void setCurso(String curso) {
		this.curso = curso;
	}

	public int getUsuarioid() {
		return this.usuarioid;
	}

	public void setUsuarioid(int usuarioid) {
		this.usuarioid = usuarioid;
	}

	public String getUsuarioCreacion() {
		return this.usuarioCreacion;
	}

	public void setUsuarioCreacion(String usuarioCreacion) {
		this.usuarioCreacion = usuarioCreacion;
	}

	public Date getFechaCreacion() {
		return this.fechaCreacion;
	}

	public void setFechaCreacion(Date fechaCreacion) {
		this.fechaCreacion = fechaCreacion;
	}

	public String getUsuarioModifica() {
		return this.usuarioModifica;
	}

	public void setUsuarioModifica(String usuarioModifica) {
		this.usuarioModifica = usuarioModifica;
	}

	public Date getFechaModifica() {
		return this.fechaModifica;
	}

	public void setFechaModifica(Date fechaModifica) {
		this.fechaModifica = fechaModifica;
	}

	public Set<Almuerzo> getAlmuerzos() {
		return this.almuerzos;
	}

	public void setAlmuerzos(Set<Almuerzo> almuerzos) {
		this.almuerzos = almuerzos;
	}

}
