package co.edu.usbcali.modelo;
// Generated 12-mar-2018 23:23:38 by Hibernate Tools 5.2.3.Final

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * MenuSemana generated by hbm2java
 */
public class MenuSemana implements java.io.Serializable {

	private long id;
	private Bebida sopa;
	private Principio principio;
	private Proteina proteina;
	private String dia;
	private Integer idBebida;
	private String estado;
	private Date fechaInicio;
	private Date fechaFin;
	private String usuarioCreacion;
	private Date fechaCreacion;
	private String usuarioModifica;
	private Date fechaModifica;
	private Set<Almuerzo> almuerzos = new HashSet<Almuerzo>(0);

	public MenuSemana() {
	}

	public MenuSemana(long id, Bebida sopa, Principio principio, Proteina proteina) {
		this.id = id;
		this.sopa = sopa;
		this.principio = principio;
		this.proteina = proteina;
	}

	public MenuSemana(long id, Bebida sopa, Principio principio, Proteina proteina, String dia, Integer idBebida,
			String estado, Date fechaInicio, Date fechaFin, String usuarioCreacion, Date fechaCreacion,
			String usuarioModifica, Date fechaModifica, Set<Almuerzo> almuerzos) {
		this.id = id;
		this.sopa = sopa;
		this.principio = principio;
		this.proteina = proteina;
		this.dia = dia;
		this.idBebida = idBebida;
		this.estado = estado;
		this.fechaInicio = fechaInicio;
		this.fechaFin = fechaFin;
		this.usuarioCreacion = usuarioCreacion;
		this.fechaCreacion = fechaCreacion;
		this.usuarioModifica = usuarioModifica;
		this.fechaModifica = fechaModifica;
		this.almuerzos = almuerzos;
	}

	public long getId() {
		return this.id;
	}

	public void setId(long id) {
		this.id = id;
	}

	public Bebida getSopa() {
		return this.sopa;
	}

	public void setSopa(Bebida sopa) {
		this.sopa = sopa;
	}

	public Principio getPrincipio() {
		return this.principio;
	}

	public void setPrincipio(Principio principio) {
		this.principio = principio;
	}

	public Proteina getProteina() {
		return this.proteina;
	}

	public void setProteina(Proteina proteina) {
		this.proteina = proteina;
	}

	public String getDia() {
		return this.dia;
	}

	public void setDia(String dia) {
		this.dia = dia;
	}

	public Integer getIdBebida() {
		return this.idBebida;
	}

	public void setIdBebida(Integer idBebida) {
		this.idBebida = idBebida;
	}

	public String getEstado() {
		return this.estado;
	}

	public void setEstado(String estado) {
		this.estado = estado;
	}

	public Date getFechaInicio() {
		return this.fechaInicio;
	}

	public void setFechaInicio(Date fechaInicio) {
		this.fechaInicio = fechaInicio;
	}

	public Date getFechaFin() {
		return this.fechaFin;
	}

	public void setFechaFin(Date fechaFin) {
		this.fechaFin = fechaFin;
	}

	public String getUsuarioCreacion() {
		return this.usuarioCreacion;
	}

	public void setUsuarioCreacion(String usuarioCreacion) {
		this.usuarioCreacion = usuarioCreacion;
	}

	public Date getFechaCreacion() {
		return this.fechaCreacion;
	}

	public void setFechaCreacion(Date fechaCreacion) {
		this.fechaCreacion = fechaCreacion;
	}

	public String getUsuarioModifica() {
		return this.usuarioModifica;
	}

	public void setUsuarioModifica(String usuarioModifica) {
		this.usuarioModifica = usuarioModifica;
	}

	public Date getFechaModifica() {
		return this.fechaModifica;
	}

	public void setFechaModifica(Date fechaModifica) {
		this.fechaModifica = fechaModifica;
	}

	public Set<Almuerzo> getAlmuerzos() {
		return this.almuerzos;
	}

	public void setAlmuerzos(Set<Almuerzo> almuerzos) {
		this.almuerzos = almuerzos;
	}

}
