package co.edu.usbcali.modelo;
// Generated 10-mar-2018 20:23:35 by Hibernate Tools 5.2.3.Final

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Sopa generated by hbm2java
 */
public class Sopa implements java.io.Serializable {

	private int idsopa;
	private String nombre;
	private byte[] descripcion;
	private String usuarioCreacion;
	private Date fechaCreacion;
	private String usuarioModifica;
	private Date fechaModifica;
	private Set<MenuSemana> menuSemanas = new HashSet<MenuSemana>(0);

	public Sopa() {
	}

	public Sopa(int idsopa) {
		this.idsopa = idsopa;
	}

	public Sopa(int idsopa, String nombre, byte[] descripcion, String usuarioCreacion, Date fechaCreacion,
			String usuarioModifica, Date fechaModifica, Set<MenuSemana> menuSemanas) {
		this.idsopa = idsopa;
		this.nombre = nombre;
		this.descripcion = descripcion;
		this.usuarioCreacion = usuarioCreacion;
		this.fechaCreacion = fechaCreacion;
		this.usuarioModifica = usuarioModifica;
		this.fechaModifica = fechaModifica;
		this.menuSemanas = menuSemanas;
	}

	public int getIdsopa() {
		return this.idsopa;
	}

	public void setIdsopa(int idsopa) {
		this.idsopa = idsopa;
	}

	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	public byte[] getDescripcion() {
		return this.descripcion;
	}

	public void setDescripcion(byte[] descripcion) {
		this.descripcion = descripcion;
	}

	public String getUsuarioCreacion() {
		return this.usuarioCreacion;
	}

	public void setUsuarioCreacion(String usuarioCreacion) {
		this.usuarioCreacion = usuarioCreacion;
	}

	public Date getFechaCreacion() {
		return this.fechaCreacion;
	}

	public void setFechaCreacion(Date fechaCreacion) {
		this.fechaCreacion = fechaCreacion;
	}

	public String getUsuarioModifica() {
		return this.usuarioModifica;
	}

	public void setUsuarioModifica(String usuarioModifica) {
		this.usuarioModifica = usuarioModifica;
	}

	public Date getFechaModifica() {
		return this.fechaModifica;
	}

	public void setFechaModifica(Date fechaModifica) {
		this.fechaModifica = fechaModifica;
	}

	public Set<MenuSemana> getMenuSemanas() {
		return this.menuSemanas;
	}

	public void setMenuSemanas(Set<MenuSemana> menuSemanas) {
		this.menuSemanas = menuSemanas;
	}

}
