package co.edu.usbcali.modelo;
// Generated 11-abr-2018 21:14:45 by Hibernate Tools 3.5.0.Final

import java.math.BigDecimal;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Principio generated by hbm2java
 */
public class Principio implements java.io.Serializable {

	private BigDecimal id;
	private String nombre;
	private String descripcion;
	private String estado;
	private String usuarioCreacion;
	private String usuarioModifica;
	private Date fechaCreacion;
	private Date fechaModifica;
	private Set<MenuSemana> menuSemanas = new HashSet<MenuSemana>(0);

	public Principio() {
	}

	public Principio(BigDecimal id) {
		this.id = id;
	}

	public Principio(BigDecimal id, String nombre, String descripcion, String estado, String usuarioCreacion,
			String usuarioModifica, Date fechaCreacion, Date fechaModifica, Set<MenuSemana> menuSemanas) {
		this.id = id;
		this.nombre = nombre;
		this.descripcion = descripcion;
		this.estado = estado;
		this.usuarioCreacion = usuarioCreacion;
		this.usuarioModifica = usuarioModifica;
		this.fechaCreacion = fechaCreacion;
		this.fechaModifica = fechaModifica;
		this.menuSemanas = menuSemanas;
	}

	public BigDecimal getId() {
		return this.id;
	}

	public void setId(BigDecimal id) {
		this.id = id;
	}

	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	public String getDescripcion() {
		return this.descripcion;
	}

	public void setDescripcion(String descripcion) {
		this.descripcion = descripcion;
	}

	public String getEstado() {
		return this.estado;
	}

	public void setEstado(String estado) {
		this.estado = estado;
	}

	public String getUsuarioCreacion() {
		return this.usuarioCreacion;
	}

	public void setUsuarioCreacion(String usuarioCreacion) {
		this.usuarioCreacion = usuarioCreacion;
	}

	public String getUsuarioModifica() {
		return this.usuarioModifica;
	}

	public void setUsuarioModifica(String usuarioModifica) {
		this.usuarioModifica = usuarioModifica;
	}

	public Date getFechaCreacion() {
		return this.fechaCreacion;
	}

	public void setFechaCreacion(Date fechaCreacion) {
		this.fechaCreacion = fechaCreacion;
	}

	public Date getFechaModifica() {
		return this.fechaModifica;
	}

	public void setFechaModifica(Date fechaModifica) {
		this.fechaModifica = fechaModifica;
	}

	public Set<MenuSemana> getMenuSemanas() {
		return this.menuSemanas;
	}

	public void setMenuSemanas(Set<MenuSemana> menuSemanas) {
		this.menuSemanas = menuSemanas;
	}

}
